version: 3

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: sdorg-application:latest
    ports:
    - 9094:9094
    networks:
      - sdorg-group-network
    depends_on:
      - postgres
  postgres:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres
    environment:
      - POSTGRES_USER: sdorg-db-user
      - POSTGRES_PASSWORD: sdorg-db-password
    volumes:
    - postgresql:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data
    networks:
      - sdorg-group-network
  adminer:
    image: adminer:4.8.1-standalone
    restart: on-failure
    container_name: adminer
    ports:
    - 8080:8080
    environment:
      - ADMINER_DESIGN=nette
      - ADMIN_DEFAULT_SERVER=postgres
    networks:
      - sdorg-group-network
    depends_on:
      - postgres
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    container_name: redis
    ports:
    - 6379:6379
    networks:
      - sdorg-group-network
networks:
  sdorg-group-network:
    driver: bridge
volumes:
  postgrsql:
  postgresql_data:

