server:
  port: 9093
  compression:
    enabled: true
  shutdown: graceful
spring:
  application:
    name: Secure Device of an organization
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sdorg
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgrSQLDialect
  redis:
    host: localhost
    port: 6379
  jackson:
    date-format: dd/MM/YYYY
    locale: en
    time-zone: "GMT+2"
logging:
  level: debug
  file:
    name: sdorg.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

